from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    #These are read by LLM 
    #Define the schema for the agent's input data and add operator will be used to combine the list of messages
    messages: Annotated[list,add]= Field(..., description="List of messages to be processed by the agent")
    #when using messages with append and add , the entire history will be passed
    # which makes it difficult to curate question from latest message, so we will also pass the latest message separately to curate question
    #so we add user_question and latest_message to the schema to help curate the question from the latest message
    user_question: str= Field(..., description="The original question asked by the user")
    #latest_message: str= Field(..., description="The latest message from the user")
    curated_ques: str= Field(..., description="Curated user question to be answered by the agent")
    prompt_query_context: str=Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL query")
    generated_sql_query: str= Field(..., description="The SQL query generated by the agent based on the input messages and context")
    is_safe: Literal["Yes","No"]= Field(..., description="Indicates whether the generated SQL query is safe to execute or not. 'Yes' means safe, 'No' means unsafe.")
    comments: str=Field(..., description="Comments regarding the safety of the generated query.")
    sql_query_execution_result: str= Field(..., description="The result of executing the generated SQL query on the database")
    final_answer: str= Field(..., description="The final answer generated by the agent after processing the input messages and executing the SQL query")

    #above all is pydantic object and not dict,


class JudgeSchema(BaseModel):
    answer: Literal["Yes","No"]= Field(..., description="Indicates whether the generated SQL query is safe to execute or not. 'Yes' means safe, 'No' means unsafe.")
    comments: str= Field(..., description="Comments or feedback provided by the agent or judge  regarding the safety of the generated SQL query")



class ETLAgentSchema(BaseModel):
    messages: Annotated[list,add]= Field(..., description="List of messages to be processed by the ETL agent")


class RouterSchema(BaseModel):
    answer: Literal["sql","etl"]=Field(...,description="Indicate whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    #holds 
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")